

#ifeq ($(MODE), hase) 
#include makefile.1	
#else ifeq ($(MODE), ubuntu) 
#include makefile.2
#else 
#include makefile.3
#endif

test:
	g++ -g  test1.cpp -o test1.elf
	./test1.elf
	

test2:
	echo test2----
	
test3:
	echo test3----	
